name: upload

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  Upload:
    runs-on: ubuntu-latest

    steps:
    - name: Setup repository
      uses: actions/checkout@v2

    - name: Create files
      run:  |
        python -m pip install -U hy
        hy bing_wallpapers.hy

    - name: Commit files
      uses: EndBug/add-and-commit@v7
      with:
        message: "Upload wallpaper"
        add: "*.jpg"
